# -*- coding: utf-8 -*-
"""bot kaddelo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbCPfVw1U51KrGlbcZKKBfidJ5W1Hy3g
"""

# УСТАНАВЛИВАЕМ БИБЛИОТЕКИ
!pip install aiogram python-dotenv -q

# ИМПОРТИРУЕМ ВСЁ НЕОБХОДИМОЕ
import asyncio
import logging
from aiogram import Bot, Dispatcher, types
from aiogram.filters import Command
from aiogram.types import Message
from aiogram.enums import ParseMode
from datetime import datetime
import sys

print("=" * 50)
print("📦 УСТАНОВКА ЗАВЕРШЕНА")
print("=" * 50)
print("✅ aiogram установлен")
print("✅ python-dotenv установлен")
print("✅ Все библиотеки готовы")
print("=" * 50)

# ==== ВАШИ ДАННЫЕ ====
BOT_TOKEN = "8543540956:AAGJI5ZpqEhbyByn8rD1hKnX7gUlin4xDhU"
ADMIN_ID = 1460213585  # Ваш ID (получен от бота)

print("=" * 50)
print("🔧 ПРОВЕРКА НАСТРОЕК")
print("=" * 50)

try:
    bot = Bot(token=BOT_TOKEN)
    print("✅ Бот создан успешно!")
except Exception as e:
    print(f"❌ Ошибка создания бота: {e}")
    sys.exit()

dp = Dispatcher()
subscribers = []  # Список подписчиков (в памяти)
client_requests = []  # Список заявок от клиентов

print(f"📊 Подписчиков в памяти: {len(subscribers)}")
print(f"📋 Заявок в памяти: {len(client_requests)}")
print(f"👑 ID админа: {ADMIN_ID}")
print("=" * 50)

@dp.message(Command("start"))
async def start_command(message: Message):
    user_id = message.from_user.id
    user_name = message.from_user.full_name

    if user_id not in subscribers:
        subscribers.append(user_id)
        print(f"➕ Новый подписчик: {user_name} (ID: {user_id})")

    # Клавиатура для нового подписчика
    keyboard = types.InlineKeyboardMarkup(
        inline_keyboard=[
            [types.InlineKeyboardButton(text="📋 ПОРЯДОК ПОЛУЧЕНИЯ УСЛУГИ", callback_data="techplan_process")],
            [types.InlineKeyboardButton(text="📞 ОСТАВИТЬ ЗАЯВКУ НА КОНСУЛЬТАЦИЮ", callback_data="leave_request")],
        ]
    )

    welcome_text = f"""
👋 <b>Привет, {user_name}!</b>

✅ Вы подписались на рассылку от кадастрового инженера Глайборода И.А.!
📢 Теперь вы будете получать:
• Актуальную информацию по кадастровым услугам
• Специальные предложения и скидки

📊 Всего подписчиков: {len(subscribers)}

👇 <b> Обратите внимание:</b>
"""

    await message.answer(welcome_text, parse_mode=ParseMode.HTML, reply_markup=keyboard)

    # Дополнительная информация
    await message.answer(
        "ℹ️ <b>Дополнительные команды:</b>\n"
        "/help - справка по боту\n"
        "/unsubscribe - отписаться от рассылки",
        parse_mode=ParseMode.HTML
    )

@dp.message(Command("help"))
async def help_command(message: Message):
    help_text = """
📚 <b>Справка по Kaddelo Bot</b>

Это бот для получения информации от кадастрового инженера Глайборода И.А.

<b>Основные кнопки:</b>
• 📋 АЛГОРИТМ ПОЛУЧЕНИЯ УСЛУГИ - описание процесса работ
• 📞 ОСТАВИТЬ ЗАЯВКУ - консультация по кадастровым услугам

<b>Команды:</b>
/start - Подписаться на рассылку
/help - Эта справка
/unsubscribe - Отписаться от рассылки

<b>Для связи:</b>
Отправьте заявку через кнопку или напишите напрямую.
    """

    # Добавляем кнопки и в справку
    keyboard = types.InlineKeyboardMarkup(
        inline_keyboard=[
            [types.InlineKeyboardButton(text="📋 АЛГОРИТМ ПОЛУЧЕНИЯ УСЛУГИ", callback_data="techplan_process")],
            [types.InlineKeyboardButton(text="📞 ОСТАВИТЬ ЗАЯВКУ", callback_data="leave_request")],
        ]
    )

    await message.answer(help_text, parse_mode=ParseMode.HTML, reply_markup=keyboard)

@dp.message(Command("unsubscribe"))
async def unsubscribe_command(message: Message):
    user_id = message.from_user.id

    if user_id in subscribers:
        subscribers.remove(user_id)
        await message.answer("❌ Вы отписались от рассылки.")
        print(f"➖ Отписался: ID {user_id}")
    else:
        await message.answer("ℹ️ Вы не были подписаны.")

print("✅ Команды для пользователей добавлены!")

# ========== ОСНОВНАЯ ПАНЕЛЬ АДМИНА ==========
@dp.message(Command("admin"))
async def admin_command(message: Message):
    """Панель администратора - команда /admin"""
    if message.from_user.id != ADMIN_ID:
        await message.answer("⛔ Доступ запрещен")
        return

    keyboard = types.ReplyKeyboardMarkup(
        keyboard=[
            [types.KeyboardButton(text="📊 Статистика")],
            [types.KeyboardButton(text="📢 Сделать рассылку")],
            [types.KeyboardButton(text="🛍️ Пример акции")],
            [types.KeyboardButton(text="❌ Закрыть панель")],
        ],
        resize_keyboard=True,
        one_time_keyboard=False
    )

    admin_text = f"""
🛠️ <b>Панель администратора</b>

🤖 Бот: Kaddelo Bot
👑 Админ: {message.from_user.full_name}
👥 Подписчиков: {len(subscribers)}
📋 Заявок: {len(client_requests)}

<b>Используйте кнопки ниже:</b>
    """
    await message.answer(admin_text, reply_markup=keyboard, parse_mode=ParseMode.HTML)

# ========== КНОПКИ АДМИН-ПАНЕЛИ ==========
@dp.message(lambda message: message.text == "📊 Статистика" and message.from_user.id == ADMIN_ID)
async def stats_button(message: Message):
    """Кнопка статистики"""
    stats_text = f"""
📈 <b>Статистика Kaddelo Bot</b>

👥 Всего подписчиков: <b>{len(subscribers)}</b>
📋 Активных заявок: <b>{len(client_requests)}</b>
👑 Админ ID: <code>{ADMIN_ID}</code>

<b>Последние 5 подписчиков:</b>
"""
    if subscribers:
        last_subscribers = subscribers[-5:] if len(subscribers) >= 5 else subscribers
        for i, user_id in enumerate(last_subscribers, 1):
            stats_text += f"{i}. <code>{user_id}</code>\n"
    else:
        stats_text += "Пока нет подписчиков\n"

    if client_requests:
        stats_text += f"\n<b>Последние 3 заявки:</b>\n"
        for i, req in enumerate(client_requests[-3:], 1):
            stats_text += f"{i}. ID: <code>{req['user_id']}</code> ({req['timestamp'].strftime('%d.%m %H:%M')})\n"
    await message.answer(stats_text, parse_mode=ParseMode.HTML)

@dp.message(lambda message: message.text == "📢 Сделать рассылку" and message.from_user.id == ADMIN_ID)
async def mailing_button(message: Message):
    """Кнопка рассылки"""
    if len(subscribers) == 0:
        await message.answer("❌ Нет подписчиков для рассылки!")
        return

    mailing_text = f"""
📤 <b>Готов к рассылке!</b>

👥 Получателей: {len(subscribers)}

<b>Отправьте сообщение, которое нужно разослать:</b>
• Можно отправить текст
• Можно отправить фото с подписью
• Можно отправить видео с подписью

Сообщение будет отправлено всем {len(subscribers)} подписчикам.
"""
    await message.answer(mailing_text, parse_mode=ParseMode.HTML, reply_markup=types.ReplyKeyboardRemove())

@dp.message(lambda message: message.text == "🛍️ Пример акции" and message.from_user.id == ADMIN_ID)
async def promo_example_button(message: Message):
    """Пример акции с inline-кнопками"""
    keyboard = types.InlineKeyboardMarkup(
        inline_keyboard=[
            [types.InlineKeyboardButton(text="📋 АЛГОРИТМ ПОЛУЧЕНИЯ УСЛУГИ", callback_data="techplan_process")],
            [types.InlineKeyboardButton(text="📞 ОСТАВИТЬ ЗАЯВКУ", callback_data="leave_request")],
        ]
    )

    promo_text = """
🔥 <b>АКЦИЯ ОТ KADDELO!</b>

🎁 <b>СКИДКА 10%</b> на технический план нежилого здания:
• Гараж
• Летняя кухня
• Хозблок
⏰ Только до 20 января!

✅ Бесплатная консультация
✅ Отслеживаем результат работ
✅ Срочный заказ

💬 Оставляйте заявку прямо в боте!
"""
    await message.answer("📝 <b>Пример рекламного сообщения:</b>", parse_mode=ParseMode.HTML)
    await message.answer(promo_text, reply_markup=keyboard, parse_mode=ParseMode.HTML)
    await message.answer("📋 <i>Скопируйте этот текст для рассылки или создайте свой</i>", parse_mode=ParseMode.HTML)

# ========== INLINE-КНОПКИ ДЛЯ ПОЛЬЗОВАТЕЛЕЙ ==========
@dp.callback_query(lambda c: c.data == "techplan_process")
async def techplan_process_handler(callback_query: types.CallbackQuery):
    """Обработка кнопки с порядком изготовления техплана"""
    process_text = """
📋 <b>ПОРЯДОК ПОЛУЧЕНИЯ УСЛУГИ:</b>

1️⃣ <b>Изучение документов</b> и заключение договора
2️⃣ <b>Выезд на объект</b> для обмеров
3️⃣ <b>Подготовка документов (Технический план здания)</b>
4️⃣ <b>Передача заказчику технического плана на CD диске</b>


⏱️ <b>Срок исполнения:</b> 2-3 рабочих дня
"""
    action_keyboard = types.InlineKeyboardMarkup(
        inline_keyboard=[[types.InlineKeyboardButton(text="📞 ОСТАВИТЬ ЗАЯВКУ", callback_data="leave_request")]]
    )
    await callback_query.message.answer(process_text, parse_mode=ParseMode.HTML, reply_markup=action_keyboard)
    await callback_query.answer()

@dp.callback_query(lambda c: c.data == "leave_request")
async def leave_request_handler(callback_query: types.CallbackQuery):
    """Запрос сообщения от пользователя"""
    request_text = """
📝 <b>ОТПРАВЬТЕ ВАШЕ СООБЩЕНИЕ</b>

Напишите сообщение для кадастрового инженера.
"""
    await callback_query.message.answer(request_text, parse_mode=ParseMode.HTML)
    await callback_query.answer("✍️ Напишите ваше сообщение в чат")

# ========== ОБРАБОТКА СООБЩЕНИЙ ОТ ПОЛЬЗОВАТЕЛЕЙ ==========
@dp.message(lambda message: message.text and not message.text.startswith('/') and message.from_user.id != ADMIN_ID)
async def handle_user_message(message: Message):
    """Обработка обычных сообщений от пользователей как заявок"""
    user_id = message.from_user.id
    user_name = message.from_user.full_name or "Без имени"
    username = message.from_user.username or "Нет username"

    # Сохраняем заявку
    client_requests.append({
        'user_id': user_id,
        'user_name': user_name,
        'username': username,
        'timestamp': datetime.now(),
        'status': 'новая',
        'message': message.text
    })

    # Подтверждение пользователю
    await message.answer(
        f"✅ <b>СООБЩЕНИЕ ОТПРАВЛЕНО!</b>\n\n"
        f"Кадастровый инженер получил сообщение и свяжется с Вами в течение рабочего дня.",
        parse_mode=ParseMode.HTML
    )

    # Уведомление админу
    request_message = f"""
🚨 <b>НОВАЯ ЗАЯВКА ОТ КЛИЕНТА!</b>

👤 <b>Клиент:</b> {user_name}
📱 <b>Username:</b> @{username}
🆔 <b>ID:</b> <code>{user_id}</code>
⏰ <b>Время:</b> {datetime.now().strftime('%d.%m.%Y %H:%M')}

💬 <b>Сообщение:</b>
{message.text}
"""

    await bot.send_message(
        ADMIN_ID,
        request_message,
        parse_mode=ParseMode.HTML,
        reply_markup=types.InlineKeyboardMarkup(
            inline_keyboard=[[
                types.InlineKeyboardButton(text="💬 Написать клиенту", callback_data=f"write_{user_id}"),
                types.InlineKeyboardButton(text="✅ Взять в работу", callback_data=f"take_{user_id}"),
            ]]
        )
    )

# ========== КНОПКИ ДЛЯ АДМИНА В УВЕДОМЛЕНИИ ==========
@dp.callback_query(lambda c: c.data.startswith("write_"))
async def write_to_client_handler(callback_query: types.CallbackQuery):
    """Кнопка "Написать клиенту" - отправляем сообщение клиенту"""
    if callback_query.from_user.id != ADMIN_ID:
        await callback_query.answer("⛔ Доступ запрещен", show_alert=True)
        return

    user_id = callback_query.data.replace("write_", "")

    # Отправляем сообщение клиенту от имени бота
    try:
        await bot.send_message(
            chat_id=int(user_id),
            text="👷‍♂️ <b>Сообщение от кадастрового инженера</b>\n\n"
                 "Здравствуйте!Получил Вашу заявку,рассмотрю в течение рабочего дня.Пока Вы можете оставить свои контакты для связи и более подробной консультации по заказу",
            parse_mode=ParseMode.HTML
        )

        # Подтверждаем админу
        await callback_query.message.answer(
            f"✅ <b>Сообщение отправлено клиенту!</b>\n\n"
            f"👤 ID клиента: <code>{user_id}</code>\n"
            f"💬 Клиент получил ваше сообщение.",
            parse_mode=ParseMode.HTML
        )

        await callback_query.answer("✅ Сообщение отправлено клиенту!")

    except Exception as e:
        # Если не удалось отправить
        await callback_query.message.answer(
            f"❌ <b>Не удалось отправить сообщение</b>\n\n"
            f"Ошибка: {str(e)}\n\n"
            f"🆔 ID клиента: <code>{user_id}</code>",
            parse_mode=ParseMode.HTML
        )
        await callback_query.answer("❌ Ошибка отправки", show_alert=True)

@dp.callback_query(lambda c: c.data.startswith("take_"))
async def take_request_handler(callback_query: types.CallbackQuery):
    """Кнопка "Взять в работу" в уведомлении"""
    if callback_query.from_user.id != ADMIN_ID:
        await callback_query.answer("⛔ Доступ запрещен", show_alert=True)
        return
    user_id = callback_query.data.replace("take_", "")
    for request in client_requests:
        if str(request['user_id']) == user_id:
            request['status'] = 'в работе'
            request['taken_at'] = datetime.now()
            break
    await callback_query.message.edit_text(
        callback_query.message.text + f"\n\n✅ <b>Заявка взята в работу</b>\nВремя: {datetime.now().strftime('%H:%M')}",
        parse_mode=ParseMode.HTML
    )
    await callback_query.answer("✅ Заявка взята в работу!")

@dp.message(lambda message: message.text == "❌ Закрыть панель" and message.from_user.id == ADMIN_ID)
async def close_panel_button(message: Message):
    """Закрытие панели"""
    await message.answer("Панель закрыта. Напишите /admin чтобы открыть снова.", reply_markup=types.ReplyKeyboardRemove())

print("✅ Панель администратора добавлена!")

@dp.message(lambda message: message.from_user.id == ADMIN_ID)
async def handle_admin_mailing(message: Message):
    # Пропускаем команды, которые уже обработаны
    if message.text in ["📊 Статистика", "📢 Сделать рассылку", "🛍️ Пример акции", "❌ Закрыть панель"]:
        return

    # Если нет подписчиков
    if len(subscribers) == 0:
        await message.answer("❌ Нет подписчиков для рассылки!")
        return

    # Начинаем рассылку
    await message.answer(f"🔄 Начинаю рассылку на {len(subscribers)} пользователей...")

    success_count = 0
    failed_count = 0

    # Рассылаем всем подписчикам
    for user_id in subscribers:
        try:
            # Если это фото
            if message.photo:
                await bot.send_photo(
                    chat_id=user_id,
                    photo=message.photo[-1].file_id,
                    caption=message.caption or "",
                    parse_mode=ParseMode.HTML
                )

            # Если это видео
            elif message.video:
                await bot.send_video(
                    chat_id=user_id,
                    video=message.video.file_id,
                    caption=message.caption or "",
                    parse_mode=ParseMode.HTML
                )

            # Если это просто текст
            else:
                await bot.send_message(
                    chat_id=user_id,
                    text=message.text or message.caption or "",
                    parse_mode=ParseMode.HTML
                )

            success_count += 1

            # Небольшая пауза, чтобы не превысить лимиты Telegram
            await asyncio.sleep(0.05)

        except Exception as e:
            failed_count += 1
            print(f"❌ Ошибка отправки пользователю {user_id}: {e}")

    # Отчет о рассылке
    report_text = f"""
✅ <b>Рассылка завершена!</b>

📊 <b>Отчет:</b>
├ Успешно отправлено: <b>{success_count}</b>
├ Не удалось отправить: <b>{failed_count}</b>
└ Всего получателей: <b>{len(subscribers)}</b>

<i>Для новой рассылки снова нажмите "📢 Сделать рассылку"</i>
"""

    await message.answer(report_text, parse_mode=ParseMode.HTML)

    # Показываем статистику в консоли Colab
    print("=" * 50)
    print("📊 ОТЧЕТ О РАССЫЛКЕ")
    print("=" * 50)
    print(f"✅ Успешно: {success_count}")
    print(f"❌ Ошибки: {failed_count}")
    print(f"👥 Всего: {len(subscribers)}")
    print("=" * 50)

print("✅ Система рассылки готова!")

async def main():
    print("=" * 60)
    print("🚀 ЗАПУСКАЕМ БОТА КАДАСТРОВОГО ИНЖЕНЕРА")
    print("=" * 60)

    # Проверяем подключение к боту
    try:
        bot_info = await bot.get_me()
        print(f"✅ Бот подключен: @{bot_info.username}")
        print(f"✅ Имя бота: {bot_info.first_name}")
        print(f"✅ ID бота: {bot_info.id}")
    except Exception as e:
        print(f"❌ ОШИБКА ПОДКЛЮЧЕНИЯ: {e}")
        print("Проверьте токен бота в Ячейке 2")
        return

    print("\n" + "=" * 60)
    print("📱 ИНСТРУКЦИЯ ДЛЯ РАБОТЫ:")
    print("=" * 60)
    print("1️⃣ Откройте Telegram на телефоне/компьютере")
    print("2️⃣ Найдите бота: @my_kaddelo_bot")
    print("3️⃣ Напишите боту команду /start (чтобы подписаться)")
    print("\n4️⃣ Откройте бота со своего аккаунта (админа)")
    print("5️⃣ Напишите команду /admin")
    print("6️⃣ Используйте кнопки для управления:")
    print("   📊 Статистика - посмотреть подписчиков и заявки")
    print("   📢 Сделать рассылку - отправить сообщение всем")
    print("   🛍️ Пример акции - посмотреть шаблон с кнопками")
    print("   ❌ Закрыть панель - убрать кнопки")
    print("\n" + "=" * 60)
    print("⚠️  ВАЖНО: Бот работает пока открыт Colab")
    print("⏹️  Для остановки: Нажмите Stop в Colab")
    print("=" * 60 + "\n")

    # Запускаем бота
    try:
        await dp.start_polling(bot)
    except Exception as e:
        print(f"❌ Ошибка при работе бота: {e}")
    finally:
        await bot.session.close()
        print("👋 Бот остановлен")

print("🎯 Нажмите ▶️ чтобы запустить бота...")
print("После запуска перейдите в Telegram")

# Запуск в Colab с использованием nest_asyncio
!pip install nest_asyncio -q
import nest_asyncio
nest_asyncio.apply()

import asyncio
asyncio.run(main())